#!/usr/bin/env python3
"""Verify sandbox writer skeleton safety boundaries."""

from __future__ import annotations

from pathlib import Path

from sandbox_writer_invariant import collect_sandbox_writer_invariant_failures


REQUIRED_FILES = [
    "scripts/powershell/Invoke-MaxineSandboxResolverWrite.ps1",
    "scripts/powershell/Invoke-MaxineSandboxRollback.ps1",
    "scripts/powershell/Invoke-MaxineSandboxReceiptInspect.ps1",
    "scripts/powershell/Invoke-MaxineSandboxReviewPacketBuild.ps1",
    "scripts/powershell/Invoke-MaxineSandboxReviewPacketInspect.ps1",
    "scripts/powershell/Invoke-MaxineSandboxReviewDecisionRecord.ps1",
    "scripts/powershell/Invoke-MaxineSandboxReviewDecisionInspect.ps1",
    "scripts/powershell/Invoke-MaxineSandboxWorkflowRun.ps1",
    "scripts/powershell/Invoke-MaxineSandboxWorkflowInspect.ps1",
    "scripts/powershell/Invoke-MaxineSandboxEvidenceBundleExport.ps1",
    "scripts/powershell/Invoke-MaxineSandboxOperatorSummary.ps1",
    "scripts/powershell/Invoke-MaxineProjectInventoryRead.ps1",
    "scripts/powershell/Invoke-MaxineProjectInventoryInspect.ps1",
    "scripts/powershell/Invoke-MaxineAssetCandidateInventoryRead.ps1",
    "scripts/powershell/Invoke-MaxineAssetCandidateInventoryInspect.ps1",
    "scripts/powershell/Invoke-MaxineAssetCandidateReviewPacketBuild.ps1",
    "scripts/powershell/Invoke-MaxineAssetCandidateReviewPacketInspect.ps1",
    "scripts/powershell/Invoke-MaxineAssetCandidateEvidenceBundleExport.ps1",
    "scripts/powershell/Invoke-MaxineProductResolutionProposalBuild.ps1",
    "scripts/powershell/Invoke-MaxineProductResolutionProposalInspect.ps1",
    "scripts/powershell/Invoke-MaxineProductResolutionProposalBundleExport.ps1",
    "scripts/powershell/Invoke-MaxineApEvidenceImport.ps1",
    "scripts/powershell/Invoke-MaxineApEvidenceInspect.ps1",
    "scripts/powershell/Invoke-MaxineApEvidenceBundleExport.ps1",
    "scripts/powershell/Invoke-MaxineApExecutionPreflightBuild.ps1",
    "scripts/powershell/Invoke-MaxineApExecutionPreflightInspect.ps1",
    "scripts/powershell/Invoke-MaxineApExecutionPreflightBundleExport.ps1",
    "scripts/powershell/Invoke-MaxineApDiagnosticExecution.ps1",
    "scripts/powershell/Invoke-MaxineApDiagnosticExecutionInspect.ps1",
    "scripts/powershell/Invoke-MaxineApDiagnosticExecutionBundleExport.ps1",
    "scripts/powershell/Invoke-MaxineApBinaryDiscoveryRead.ps1",
    "scripts/powershell/Invoke-MaxineApBinaryDiscoveryInspect.ps1",
    "scripts/powershell/Invoke-MaxineApBinaryPreflightBuild.ps1",
    "scripts/powershell/Invoke-MaxineApRealBinaryDiagnosticExecution.ps1",
    "scripts/powershell/Invoke-MaxineApRealBinaryDiagnosticInspect.ps1",
    "scripts/powershell/Invoke-MaxineApRealBinaryDiagnosticBundleExport.ps1",
    "schemas/maxine_sandbox_resolver_write_plan.schema.json",
    "schemas/maxine_sandbox_write_receipt.schema.json",
    "schemas/maxine_sandbox_receipt_index.schema.json",
    "schemas/maxine_sandbox_review_packet.schema.json",
    "schemas/maxine_sandbox_review_decision.schema.json",
    "schemas/maxine_sandbox_workflow_run.schema.json",
    "schemas/maxine_sandbox_evidence_bundle.schema.json",
    "schemas/maxine_asset_candidate_inventory.schema.json",
    "schemas/maxine_asset_candidate_review_packet.schema.json",
    "schemas/maxine_asset_candidate_evidence_bundle.schema.json",
    "schemas/maxine_product_resolution_proposal.schema.json",
    "schemas/maxine_product_resolution_proposal_bundle.schema.json",
    "schemas/maxine_ap_evidence_import.schema.json",
    "schemas/maxine_ap_evidence_bundle.schema.json",
    "schemas/maxine_ap_execution_preflight.schema.json",
    "schemas/maxine_ap_execution_preflight_bundle.schema.json",
    "schemas/maxine_ap_diagnostic_execution.schema.json",
    "schemas/maxine_ap_diagnostic_execution_bundle.schema.json",
    "schemas/maxine_ap_binary_discovery.schema.json",
    "schemas/maxine_ap_binary_preflight.schema.json",
    "schemas/maxine_ap_real_binary_diagnostic_execution.schema.json",
    "schemas/maxine_ap_real_binary_diagnostic_bundle.schema.json",
    "schemas/maxine_dcc_conform_report.schema.json",
    "schemas/maxine_material_uv_qc_report.schema.json",
    "schemas/maxine_animation_smoke_report.schema.json",
    "schemas/maxine_manual_hero_review_report.schema.json",
    "schemas/maxine_ci_artifact_retention_report.schema.json",
    "schemas/maxine_release_package_bundle_report.schema.json",
    "schemas/maxine_release_promotion_decision_report.schema.json",
    "schemas/maxine_source_product_evidence_resolver_report.schema.json",
    "schemas/maxine_manifest_qc_attachment.schema.json",
    "schemas/maxine_capability_matrix.schema.json",
    "examples/sandbox/receipts/index.json",
    "examples/sandbox/evidence-bundles/.gitkeep",
    "examples/sandbox/operator-reports/.gitkeep",
    "examples/sandbox/project-inventory/.gitkeep",
    "examples/sandbox/asset-candidates/.gitkeep",
    "examples/sandbox/asset-candidate-review-packets/.gitkeep",
    "examples/sandbox/asset-candidate-evidence-bundles/.gitkeep",
    "examples/sandbox/product-resolution-proposals/.gitkeep",
    "examples/sandbox/product-resolution-proposal-bundles/.gitkeep",
    "examples/sandbox/ap-evidence-imports/.gitkeep",
    "examples/sandbox/ap-evidence-bundles/.gitkeep",
    "examples/sandbox/ap-execution-preflights/.gitkeep",
    "examples/sandbox/ap-execution-preflight-bundles/.gitkeep",
    "examples/sandbox/ap-diagnostic-executions",
    "examples/sandbox/ap-diagnostic-execution-bundles",
    "examples/sandbox/ap-binary-discovery/.gitkeep",
    "examples/sandbox/ap-binary-preflights/.gitkeep",
    "examples/sandbox/ap-real-binary-diagnostic-executions/.gitkeep",
    "examples/sandbox/ap-real-binary-diagnostic-bundles/.gitkeep",
    "examples/dcc-conform/max_biped_v1_conform_pass.json",
    "examples/dcc-conform/max_biped_v1_conform_warn.json",
    "examples/dcc-conform/max_biped_v1_conform_fail.json",
    "examples/material-uv-qc/max_biped_v1_material_uv_pass.json",
    "examples/material-uv-qc/max_biped_v1_material_uv_warn.json",
    "examples/material-uv-qc/max_biped_v1_material_uv_fail.json",
    "examples/animation-smoke/max_biped_v1_animation_smoke_pass.json",
    "examples/animation-smoke/max_biped_v1_animation_smoke_warn.json",
    "examples/animation-smoke/max_biped_v1_animation_smoke_fail.json",
    "examples/sandbox/animation-smoke-evidence/pilot-candidates/max_biped_v1_animation_smoke_controlled_real.fixture.json",
    "examples/manual-hero-review/max_biped_v1_manual_hero_review_pass.json",
    "examples/manual-hero-review/max_biped_v1_manual_hero_review_warn.json",
    "examples/manual-hero-review/max_biped_v1_manual_hero_review_pending.json",
    "examples/manual-hero-review/max_biped_v1_manual_hero_review_fail.json",
    "examples/sandbox/manual-hero-review-evidence/pilot-candidates/max_biped_v1_manual_hero_review_controlled_real.fixture.json",
    "schemas/maxine_aaa_performance_budget_report.schema.json",
    "examples/aaa-performance-budget/max_biped_v1_aaa_performance_budget_pass.json",
    "examples/aaa-performance-budget/max_biped_v1_aaa_performance_budget_warn.json",
    "examples/aaa-performance-budget/max_biped_v1_aaa_performance_budget_fail.json",
    "examples/sandbox/aaa-performance-budget-evidence/pilot-candidates/max_biped_v1_aaa_performance_budget_controlled_real.fixture.json",
    "tools/aaa-performance-budget/validate_aaa_performance_budget_report.py",
    "docs/maxine/specs/aaa-performance-budget-v1.md",
    "docs/maxine/specs/aaa-performance-budget-gates-v1.md",
    "examples/ci-artifact-retention/max_biped_v1_ci_artifact_retention_pass.json",
    "examples/ci-artifact-retention/max_biped_v1_ci_artifact_retention_warn.json",
    "examples/ci-artifact-retention/max_biped_v1_ci_artifact_retention_fail.json",
    "examples/release-package-bundle/max_biped_v1_release_package_bundle_pass.json",
    "examples/release-package-bundle/max_biped_v1_release_package_bundle_warn.json",
    "examples/release-package-bundle/max_biped_v1_release_package_bundle_fail.json",
    "examples/release-promotion-decision/max_biped_v1_release_promotion_decision_pass.json",
    "examples/release-promotion-decision/max_biped_v1_release_promotion_decision_warn.json",
    "examples/release-promotion-decision/max_biped_v1_release_promotion_decision_fail.json",
    "examples/source-product-evidence-resolver/max_biped_v1_source_product_resolver_pass.json",
    "examples/source-product-evidence-resolver/max_biped_v1_source_product_resolver_warn.json",
    "examples/source-product-evidence-resolver/max_biped_v1_source_product_resolver_fail.json",
    "examples/manifest-qc-attachments/max_biped_v1_skeleton_attach_pass.json",
    "examples/manifest-qc-attachments/max_biped_v1_dcc_conform_attach_warn.json",
    "examples/manifest-qc-attachments/max_biped_v1_manual_hero_review_attach_pass.json",
    "examples/manifest-qc-attachments/max_biped_v1_source_product_attach_fail.json",
    "examples/screenshot-evidence/max_biped_v1_screenshot_source_index.json",
    "examples/screenshot-evidence/max_biped_v1_visual_evidence_pass.json",
    "examples/screenshot-evidence/max_biped_v1_visual_evidence_warn.json",
    "examples/screenshot-evidence/max_biped_v1_visual_evidence_fail.json",
    "examples/sandbox/visual-evidence/pilot-candidates/max_biped_v1_visual_evidence_controlled_real.fixture.json",
    "examples/sandbox/evidence-sources/screenshots/pilot-shot-001.txt",
    "examples/sandbox/evidence-sources/screenshots/pilot-shot-002.txt",
    "examples/sandbox/evidence-sources/screenshots/pilot-shot-003.txt",
    "examples/sandbox/evidence-sources/screenshots/pilot-shot-004.txt",
    "examples/sandbox/evidence-sources/screenshots/pilot-shot-005.txt",
    "examples/manifests/example-release-character-qc-attach-base.manifest.json",
    "schemas/maxine_release_publication_preflight_report.schema.json",
    "examples/release-publication-preflight/max_biped_v1_release_publication_preflight_pass.json",
    "examples/release-publication-preflight/max_biped_v1_release_publication_preflight_warn.json",
    "examples/release-publication-preflight/max_biped_v1_release_publication_preflight_fail.json",
    "schemas/maxine_release_publication_request_approval_report.schema.json",
    "examples/release-publication-request-approval/max_biped_v1_release_publication_request_approval_pass.json",
    "examples/release-publication-request-approval/max_biped_v1_release_publication_request_approval_warn.json",
    "examples/release-publication-request-approval/max_biped_v1_release_publication_request_approval_fail.json",
    "schemas/maxine_release_publication_execution_admission_gate_report.schema.json",
    "examples/release-publication-execution-admission-gate/max_biped_v1_release_publication_execution_admission_gate_pass.json",
    "examples/release-publication-execution-admission-gate/max_biped_v1_release_publication_execution_admission_gate_warn.json",
    "examples/release-publication-execution-admission-gate/max_biped_v1_release_publication_execution_admission_gate_fail.json",
    "schemas/maxine_release_publication_execution_request_ledger_report.schema.json",
    "examples/release-publication-execution-request-ledger/max_biped_v1_release_publication_execution_request_ledger_pass.json",
    "examples/release-publication-execution-request-ledger/max_biped_v1_release_publication_execution_request_ledger_warn.json",
    "examples/release-publication-execution-request-ledger/max_biped_v1_release_publication_execution_request_ledger_fail.json",
    "schemas/maxine_release_publication_execution_receipt_report.schema.json",
    "examples/release-publication-execution-receipt/max_biped_v1_release_publication_execution_receipt_pass.json",
    "examples/release-publication-execution-receipt/max_biped_v1_release_publication_execution_receipt_warn.json",
    "examples/release-publication-execution-receipt/max_biped_v1_release_publication_execution_receipt_fail.json",
    "schemas/maxine_release_publication_evidence_integrity_index_report.schema.json",
    "examples/release-publication-evidence-integrity-index/max_biped_v1_release_publication_evidence_integrity_index_pass.json",
    "examples/release-publication-evidence-integrity-index/max_biped_v1_release_publication_evidence_integrity_index_warn.json",
    "examples/release-publication-evidence-integrity-index/max_biped_v1_release_publication_evidence_integrity_index_fail.json",
    "schemas/maxine_release_publication_chain_audit_bundle_report.schema.json",
    "examples/release-publication-chain-audit-bundle/max_biped_v1_release_publication_chain_audit_bundle_pass.json",
    "examples/release-publication-chain-audit-bundle/max_biped_v1_release_publication_chain_audit_bundle_warn.json",
    "examples/release-publication-chain-audit-bundle/max_biped_v1_release_publication_chain_audit_bundle_fail.json",
    "schemas/maxine_release_publication_execution_handoff_report.schema.json",
    "examples/release-publication-execution-handoff/max_biped_v1_release_publication_execution_handoff_pass.json",
    "examples/release-publication-execution-handoff/max_biped_v1_release_publication_execution_handoff_warn.json",
    "examples/release-publication-execution-handoff/max_biped_v1_release_publication_execution_handoff_fail.json",
    "schemas/maxine_release_publication_execution_admission_request_packet_report.schema.json",
    "examples/release-publication-execution-admission-request-packet/max_biped_v1_release_publication_execution_admission_request_packet_pass.json",
    "examples/release-publication-execution-admission-request-packet/max_biped_v1_release_publication_execution_admission_request_packet_warn.json",
    "examples/release-publication-execution-admission-request-packet/max_biped_v1_release_publication_execution_admission_request_packet_fail.json",
    "schemas/maxine_release_publication_gate_set_report.schema.json",
    "schemas/maxine_screenshot_evidence_report.schema.json",
    "examples/release-publication-gate-set/max_biped_v1_release_publication_gate_set_pass.json",
    "examples/release-publication-gate-set/max_biped_v1_release_publication_gate_set_warn.json",
    "examples/release-publication-gate-set/max_biped_v1_release_publication_gate_set_fail.json",
    "examples/manifests/example-release-publication-gate-set-pass.manifest.json",
    "examples/manifests/example-release-publication-gate-set-warn.manifest.json",
    "examples/manifests/example-release-publication-gate-set-fail.manifest.json",
    "examples/capabilities/maxine-capability-matrix.json",
    "schemas/maxine_execution_admission_candidate_matrix.schema.json",
    "examples/execution-admission/execution_admission_candidate_matrix_v1.json",
    "tools/execution-admission/validate_execution_admission_candidate_matrix.py",
    "docs/maxine/execution-admission/execution-admission-candidate-matrix-v1.md",
    "schemas/maxine_execution_admission_preflight_contracts.schema.json",
    "examples/execution-admission/execution_admission_preflight_contracts_v1.json",
    "tools/execution-admission/validate_execution_admission_preflight_contracts.py",
    "docs/maxine/execution-admission/execution-admission-preflight-contracts-v1.md",
    "schemas/maxine_execution_admission_preflight_proof_packages.schema.json",
    "examples/execution-admission/execution_admission_preflight_proof_packages_v1.json",
    "tools/execution-admission/validate_execution_admission_preflight_proof_packages.py",
    "docs/maxine/execution-admission/execution-admission-preflight-proof-packages-v1.md",
    "tests/pytest/test_execution_admission_preflight_proof_packages.py",
    "schemas/maxine_execution_admission_readiness_rollup.schema.json",
    "examples/execution-admission/execution_admission_readiness_rollup_v1.json",
    "tools/execution-admission/validate_execution_admission_readiness_rollup.py",
    "docs/maxine/execution-admission/execution-admission-readiness-rollup-v1.md",
    "tests/pytest/test_execution_admission_readiness_rollup.py",
    "schemas/maxine_release_candidate_publication_dry_run_plan.schema.json",
    "examples/execution-admission/release_candidate_package_publish_dry_run_plan_v1.json",
    "tools/execution-admission/validate_release_candidate_publication_dry_run_plan.py",
    "docs/maxine/execution-admission/release-candidate-package-publish-dry-run-planning-v1.md",
    "tests/pytest/test_release_candidate_publication_dry_run_plan.py",
    "schemas/maxine_release_candidate_publication_dry_run_receipt.schema.json",
    "examples/execution-admission/release_candidate_package_publish_dry_run_receipt_contract_v1.json",
    "examples/execution-admission/release_candidate_package_publish_dry_run_receipt_blocked_v1.json",
    "tools/execution-admission/validate_release_candidate_publication_dry_run_receipt.py",
    "docs/maxine/execution-admission/release-candidate-package-publish-dry-run-receipt-contract-v1.md",
    "tests/pytest/test_release_candidate_publication_dry_run_receipt_contract.py",
    "schemas/maxine_release_candidate_publication_dry_run_admission_blockers.schema.json",
    "examples/execution-admission/release_candidate_package_publish_dry_run_admission_blockers_v1.json",
    "tools/execution-admission/validate_release_candidate_publication_dry_run_admission_blockers.py",
    "docs/maxine/execution-admission/release-candidate-package-publish-dry-run-admission-blockers-v1.md",
    "tests/pytest/test_release_candidate_publication_dry_run_admission_blockers.py",
    "schemas/maxine_release_candidate_publication_dry_run_operator_approval_packet.schema.json",
    "examples/execution-admission/release_candidate_package_publish_dry_run_operator_approval_packet_v1.json",
    "tools/execution-admission/validate_release_candidate_publication_dry_run_operator_approval_packet.py",
    "docs/maxine/execution-admission/release-candidate-package-publish-dry-run-operator-approval-packet-v1.md",
    "tests/pytest/test_release_candidate_publication_dry_run_operator_approval_packet.py",
    "schemas/maxine_release_candidate_publication_dry_run_operator_approval_packet_completeness.schema.json",
    "examples/execution-admission/release_candidate_package_publish_dry_run_operator_approval_packet_completeness_v1.json",
    "tools/execution-admission/validate_release_candidate_publication_dry_run_operator_approval_packet_completeness.py",
    "docs/maxine/execution-admission/release-candidate-package-publish-dry-run-operator-approval-packet-completeness-v1.md",
    "tests/pytest/test_release_candidate_publication_dry_run_operator_approval_packet_completeness.py",
    "schemas/maxine_release_candidate_publication_dry_run_approval_request_readiness.schema.json",
    "examples/execution-admission/release_candidate_package_publish_dry_run_approval_request_readiness_v1.json",
    "tools/execution-admission/validate_release_candidate_publication_dry_run_approval_request_readiness.py",
    "docs/maxine/execution-admission/release-candidate-package-publish-dry-run-approval-request-readiness-v1.md",
    "tests/pytest/test_release_candidate_publication_dry_run_approval_request_readiness.py",
    "examples/sandbox/review-packets/.gitkeep",
    "examples/sandbox/review-decisions/.gitkeep",
    "examples/sandbox/workflow-runs/.gitkeep",
    "examples/sandbox/staging/.gitkeep",
    "tools/dcc-conform/validate_dcc_conform_report.py",
    "docs/maxine/specs/dcc-conform-v1.md",
    "tools/material-uv-qc/validate_material_uv_qc_report.py",
    "docs/maxine/specs/material-uv-qc-v1.md",
    "tools/animation-smoke/validate_animation_smoke_report.py",
    "docs/maxine/specs/animation-smoke-v1.md",
    "docs/maxine/specs/controlled-real-animation-smoke-evidence-v1.md",
    "docs/maxine/specs/controlled-real-visual-evidence-v1.md",
    "tools/manual-hero-review/validate_manual_hero_review_report.py",
    "docs/maxine/specs/manual-hero-review-v1.md",
    "docs/maxine/specs/manual-hero-review-controlled-real-evidence-v1.md",
    "tools/ci-artifact-retention/validate_ci_artifact_retention_report.py",
    "docs/maxine/specs/ci-artifact-retention-v1.md",
    "tools/release-package-bundle/validate_release_package_bundle_report.py",
    "docs/maxine/specs/release-package-bundle-v1.md",
    "tools/release-promotion-decision/validate_release_promotion_decision_report.py",
    "docs/maxine/specs/release-promotion-decision-v1.md",
    "tools/source-product-evidence-resolver/validate_source_product_evidence_resolver_report.py",
    "docs/maxine/specs/source-product-evidence-resolver-v1.md",
    "tools/manifest-validator/attach_qc_gate.py",
    "docs/maxine/specs/manifest-qc-attachment-pipeline-v1.md",
    "tools/release-lane/validate_pilot_release_chain.py",
    "examples/release-lane-gate-chain/max_biped_v1_release_lane_gate_chain.json",
    "examples/manifests/example-release-character-pilot-chain.manifest.json",
    "docs/maxine/specs/pilot-release-package-chain-v1.md",
    "tools/release-lane/run_pilot_release_chain_validation.py",
    "tools/release-lane/prove_pilot_release_chain.py",
    "examples/manifests/example-release-character-pilot-chain-base.manifest.json",
    "docs/maxine/specs/pilot-release-chain-validation-runner-v1.md",
    "docs/maxine/specs/pilot-release-chain-ci-proof-v1.md",
    "tools/screenshot-evidence/extract_screenshot_evidence_index.py",
    "docs/maxine/specs/screenshot-evidence-extractor-v1.md",
    "docs/maxine/release-lane-gate-chain-v1.md",
    "tools/release-publication-preflight/validate_release_publication_preflight_report.py",
    "docs/maxine/specs/release-publication-preflight-v1.md",
    "tools/release-publication-request-approval/validate_release_publication_request_approval_report.py",
    "docs/maxine/specs/release-publication-request-approval-v1.md",
    "tools/release-publication-execution-admission-gate/validate_release_publication_execution_admission_gate_report.py",
    "docs/maxine/specs/release-publication-execution-admission-gate-v1.md",
    "tools/release-publication-execution-request-ledger/validate_release_publication_execution_request_ledger_report.py",
    "docs/maxine/specs/release-publication-execution-request-ledger-v1.md",
    "tools/release-publication-execution-receipt/validate_release_publication_execution_receipt_report.py",
    "docs/maxine/specs/release-publication-execution-receipt-v1.md",
    "tools/release-publication-evidence-integrity-index/validate_release_publication_evidence_integrity_index_report.py",
    "docs/maxine/specs/release-publication-evidence-integrity-index-v1.md",
    "tools/release-publication-chain-audit-bundle/validate_release_publication_chain_audit_bundle_report.py",
    "docs/maxine/specs/release-publication-chain-audit-bundle-v1.md",
    "tools/release-publication-execution-handoff/validate_release_publication_execution_handoff_report.py",
    "docs/maxine/specs/release-publication-execution-handoff-v1.md",
    "tools/release-publication-execution-admission-request-packet/validate_release_publication_execution_admission_request_packet_report.py",
    "docs/maxine/specs/release-publication-execution-admission-request-packet-v1.md",
    "tools/release-publication-gate-set/validate_release_publication_gate_set_report.py",
    "docs/maxine/specs/release-publication-gate-set-v1.md",
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def check_exists(root: Path, rel_paths: list[str], failures: list[str]) -> None:
    for rel in rel_paths:
        if not (root / rel).exists():
            failures.append(f"missing required file: {rel}")


def main() -> int:
    root = repo_root()
    failures: list[str] = []

    check_exists(root, REQUIRED_FILES, failures)
    failures.extend(collect_sandbox_writer_invariant_failures(root))

    if failures:
        print("FAIL: sandbox writer safety verification failed.")
        for failure in failures:
            print(f" - {failure}")
        return 1

    print("PASS: sandbox writer admitted-only safety verification passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
